// generated by stringer -type=BroadcastType; DO NOT EDIT

package gemist

import "fmt"

const _BroadcastType_name = "VideoAudio"

var _BroadcastType_index = [...]uint8{0, 5, 10}

func (i BroadcastType) String() string {
	if i < 0 || i >= BroadcastType(len(_BroadcastType_index)-1) {
		return fmt.Sprintf("BroadcastType(%d)", i)
	}
	return _BroadcastType_name[_BroadcastType_index[i]:_BroadcastType_index[i+1]]
}
